import { useCallback, useMemo } from 'react';

import { useSettingsStore } from '@/stores/useSettingsStore';

type LocaleCode = 'en' | 'ru' | 'uz' | 'tr' | 'ar';

const translations: Record<LocaleCode, Record<string, string>> = {
  en: {
    'finance.incomeOutcomeTitle': 'Income & Outcome',
    'finance.incomeSubtitle': 'Track money that comes into your accounts',
    'finance.outcomeSubtitle': 'Track expenses with detailed categories',
    'finance.income': 'Income',
    'finance.outcome': 'Outcome',
    'finance.amount': 'Amount',
    'finance.category': 'Category',
    'finance.account': 'Account',
    'finance.currency': 'Currency',
    'finance.date': 'Date',
    'finance.note': 'Note',
    'finance.notePlaceholder': 'Add optional description or context…',
    'finance.cancel': 'Cancel',
    'finance.delete': 'Delete',
    'finance.addEntry': 'Save Entry',
    'finance.saveChanges': 'Save',
    'finance.changeDate': 'Change date',
    'finance.selectAccount': 'Select account',
    'finance.selectAccountPlaceholder': 'Select an account',
    'finance.addCategory': 'Add category',
    'finance.editCategory': 'Edit category',
    'finance.categoryPlaceholder': 'Category name',
    'finance.save': 'Save',
    'finance.selectDate': 'Select date',
    'finance.transferTitle': 'Transfer between accounts',
    'finance.transferSubtitle': 'Move money securely across wallets',
    'finance.fromAccount': 'From account',
    'finance.toAccount': 'To account',
    'finance.select': 'Select',
    'finance.balanceUnavailable': 'Balance unavailable',
    'finance.transfer': 'Transfer',
    'finance.selectFromAccount': 'Select source account',
    'finance.selectToAccount': 'Select destination account',
    'finance.debtTitle': 'Debt & Loans',
    'finance.debtSubtitle': 'Track money borrowed or lent with clarity',
    'finance.debtStatusLent': 'You lent money',
    'finance.debtStatusBorrowed': 'You borrowed money',
    'finance.borrowed': 'Borrowed',
    'finance.lent': 'Lent',
    'finance.person': 'Name / Person',
    'finance.personPlaceholder': 'Who is this debt for?',
    'finance.expectedReturn': 'Expected return date',
    'finance.selectDateHint': 'Pick a date',
    'finance.clear': 'Clear',
    'finance.expectedPlaceholder': 'No return date set',
    'finance.deleteDebtTitle': 'Delete debt',
    'finance.deleteDebtMessage': 'Are you sure you want to delete this debt? This action cannot be undone.',
  },
  ru: {
    'finance.incomeOutcomeTitle': 'Доходы и расходы',
    'finance.incomeSubtitle': 'Фиксируйте поступления на ваши счета',
    'finance.outcomeSubtitle': 'Отслеживайте расходы по категориям',
    'finance.income': 'Доход',
    'finance.outcome': 'Расход',
    'finance.amount': 'Сумма',
    'finance.category': 'Категория',
    'finance.account': 'Счёт',
    'finance.currency': 'Валюта',
    'finance.date': 'Дата',
    'finance.note': 'Заметка',
    'finance.notePlaceholder': 'Добавьте описание или детали…',
    'finance.cancel': 'Отмена',
    'finance.delete': 'Удалить',
    'finance.addEntry': 'Сохранить запись',
    'finance.saveChanges': 'Сохранить',
    'finance.changeDate': 'Изменить дату',
    'finance.selectAccount': 'Выбрать счёт',
    'finance.selectAccountPlaceholder': 'Выберите счёт',
    'finance.addCategory': 'Новая категория',
    'finance.editCategory': 'Редактировать категорию',
    'finance.categoryPlaceholder': 'Название категории',
    'finance.save': 'Сохранить',
    'finance.selectDate': 'Выберите дату',
    'finance.transferTitle': 'Перевод между счетами',
    'finance.transferSubtitle': 'Перемещайте средства между кошельками',
    'finance.fromAccount': 'Со счёта',
    'finance.toAccount': 'На счёт',
    'finance.select': 'Выбрать',
    'finance.balanceUnavailable': 'Баланс недоступен',
    'finance.transfer': 'Перевести',
    'finance.selectFromAccount': 'Выберите исходный счёт',
    'finance.selectToAccount': 'Выберите целевой счёт',
    'finance.debtTitle': 'Долги и займы',
    'finance.debtSubtitle': 'Отслеживайте занятые и одолженные суммы',
    'finance.debtStatusLent': 'Вы одолжили деньги',
    'finance.debtStatusBorrowed': 'Вы заняли деньги',
    'finance.borrowed': 'Я занял',
    'finance.lent': 'Я дал',
    'finance.person': 'Имя / Человек',
    'finance.personPlaceholder': 'Для кого этот долг?',
    'finance.expectedReturn': 'Ожидаемая дата возврата',
    'finance.selectDateHint': 'Выберите дату',
    'finance.clear': 'Очистить',
    'finance.expectedPlaceholder': 'Дата возврата не установлена',
    'finance.deleteDebtTitle': 'Удалить долг',
    'finance.deleteDebtMessage': 'Вы уверены, что хотите удалить этот долг? Действие нельзя отменить.',
  },
  uz: {
    'finance.incomeOutcomeTitle': 'Daromad va xarajatlar',
    'finance.incomeSubtitle': 'Hisoblaringizga tushgan mablag‘larni qayd eting',
    'finance.outcomeSubtitle': 'Xarajatlarni kategoriyalar bo‘yicha kuzating',
    'finance.income': 'Daromad',
    'finance.outcome': 'Xarajat',
    'finance.amount': 'Summasi',
    'finance.category': 'Kategoriya',
    'finance.account': 'Hisob',
    'finance.currency': 'Valyuta',
    'finance.date': 'Sana',
    'finance.note': 'Izoh',
    'finance.notePlaceholder': 'Qo‘shimcha izoh yoki tafsilot kiriting…',
    'finance.cancel': 'Bekor qilish',
    'finance.delete': 'O‘chirish',
    'finance.addEntry': 'Yozuvni saqlash',
    'finance.saveChanges': 'Saqlash',
    'finance.changeDate': 'Sanani o‘zgartirish',
    'finance.selectAccount': 'Hisobni tanlang',
    'finance.selectAccountPlaceholder': 'Hisobni tanlang',
    'finance.addCategory': 'Yangi kategoriya',
    'finance.editCategory': 'Kategoriyani tahrirlash',
    'finance.categoryPlaceholder': 'Kategoriya nomi',
    'finance.save': 'Saqlash',
    'finance.selectDate': 'Sanani tanlang',
    'finance.transferTitle': 'Hisoblar o‘rtasida o‘tkazma',
    'finance.transferSubtitle': 'Pulni xavfsiz tarzda hamyonlar o‘rtasida ko‘chiring',
    'finance.fromAccount': 'Qaysi hisobdan',
    'finance.toAccount': 'Qaysi hisoblarga',
    'finance.select': 'Tanlang',
    'finance.balanceUnavailable': 'Balans mavjud emas',
    'finance.transfer': 'O‘tkazish',
    'finance.selectFromAccount': 'Manba hisobni tanlang',
    'finance.selectToAccount': 'Qabul qiluvchi hisobni tanlang',
    'finance.debtTitle': 'Qarz va ssudalar',
    'finance.debtSubtitle': 'Olingan yoki berilgan mablag‘larni nazorat qiling',
    'finance.debtStatusLent': 'Siz qarz berdingiz',
    'finance.debtStatusBorrowed': 'Siz qarz oldingiz',
    'finance.borrowed': 'Qarz oldim',
    'finance.lent': 'Qarz berdim',
    'finance.person': 'Ism / Shaxs',
    'finance.personPlaceholder': 'Bu qarz kim uchun?',
    'finance.expectedReturn': 'Qaytarish sanasi',
    'finance.selectDateHint': 'Sanani tanlang',
    'finance.clear': 'Bekor qilish',
    'finance.expectedPlaceholder': 'Qaytarish sanasi belgilanmagan',
    'finance.deleteDebtTitle': "Qarzni o'chirish",
    'finance.deleteDebtMessage': "Bu qarzni butunlay o'chirib tashlamoqchimisiz? Amalni bekor qilib bo'lmaydi.",
  },
  tr: {
    'finance.incomeOutcomeTitle': 'Gelir ve Gider',
    'finance.incomeSubtitle': 'Hesaplarınıza gelen parayı takip edin',
    'finance.outcomeSubtitle': 'Harcamalarınızı detaylı kategorilerle takip edin',
    'finance.income': 'Gelir',
    'finance.outcome': 'Gider',
    'finance.amount': 'Tutar',
    'finance.category': 'Kategori',
    'finance.account': 'Hesap',
    'finance.currency': 'Para Birimi',
    'finance.date': 'Tarih',
    'finance.note': 'Not',
    'finance.notePlaceholder': 'İsteğe bağlı açıklama veya bağlam ekleyin…',
    'finance.cancel': 'İptal',
    'finance.delete': 'Sil',
    'finance.addEntry': 'Kaydı Kaydet',
    'finance.saveChanges': 'Kaydet',
    'finance.changeDate': 'Tarihi değiştir',
    'finance.selectAccount': 'Hesap seç',
    'finance.selectAccountPlaceholder': 'Bir hesap seçin',
    'finance.addCategory': 'Kategori ekle',
    'finance.editCategory': 'Kategoriyi düzenle',
    'finance.categoryPlaceholder': 'Kategori adı',
    'finance.save': 'Kaydet',
    'finance.selectDate': 'Tarih seçin',
    'finance.transferTitle': 'Hesaplar arası transfer',
    'finance.transferSubtitle': 'Parayı güvenli bir şekilde cüzdanlar arasında taşıyın',
    'finance.fromAccount': 'Hangi hesaptan',
    'finance.toAccount': 'Hangi hesaba',
    'finance.select': 'Seç',
    'finance.balanceUnavailable': 'Bakiye mevcut değil',
    'finance.transfer': 'Transfer',
    'finance.selectFromAccount': 'Kaynak hesabı seçin',
    'finance.selectToAccount': 'Hedef hesabı seçin',
    'finance.debtTitle': 'Borç ve Krediler',
    'finance.debtSubtitle': 'Ödünç alınan veya verilen parayı net şekilde takip edin',
    'finance.debtStatusLent': 'Para verdiniz',
    'finance.debtStatusBorrowed': 'Para aldınız',
    'finance.borrowed': 'Aldım',
    'finance.lent': 'Verdim',
    'finance.person': 'İsim / Kişi',
    'finance.personPlaceholder': 'Bu borç kim için?',
    'finance.expectedReturn': 'Beklenen iade tarihi',
    'finance.selectDateHint': 'Bir tarih seçin',
    'finance.clear': 'Temizle',
    'finance.expectedPlaceholder': 'İade tarihi belirlenmedi',
    'finance.deleteDebtTitle': 'Borcu sil',
    'finance.deleteDebtMessage': 'Bu borcu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
  },
  ar: {
    'finance.incomeOutcomeTitle': 'الدخل والمصروفات',
    'finance.incomeSubtitle': 'تتبع الأموال الواردة إلى حساباتك',
    'finance.outcomeSubtitle': 'تتبع النفقات بفئات تفصيلية',
    'finance.income': 'دخل',
    'finance.outcome': 'مصروف',
    'finance.amount': 'المبلغ',
    'finance.category': 'الفئة',
    'finance.account': 'الحساب',
    'finance.currency': 'العملة',
    'finance.date': 'التاريخ',
    'finance.note': 'ملاحظة',
    'finance.notePlaceholder': 'أضف وصفًا أو سياقًا اختياريًا…',
    'finance.cancel': 'إلغاء',
    'finance.delete': 'حذف',
    'finance.addEntry': 'حفظ الإدخال',
    'finance.saveChanges': 'حفظ',
    'finance.changeDate': 'تغيير التاريخ',
    'finance.selectAccount': 'اختر الحساب',
    'finance.selectAccountPlaceholder': 'اختر حسابًا',
    'finance.addCategory': 'إضافة فئة',
    'finance.editCategory': 'تحرير الفئة',
    'finance.categoryPlaceholder': 'اسم الفئة',
    'finance.save': 'حفظ',
    'finance.selectDate': 'اختر التاريخ',
    'finance.transferTitle': 'التحويل بين الحسابات',
    'finance.transferSubtitle': 'انقل الأموال بأمان بين المحافظ',
    'finance.fromAccount': 'من الحساب',
    'finance.toAccount': 'إلى الحساب',
    'finance.select': 'اختر',
    'finance.balanceUnavailable': 'الرصيد غير متاح',
    'finance.transfer': 'تحويل',
    'finance.selectFromAccount': 'اختر الحساب المصدر',
    'finance.selectToAccount': 'اختر الحساب الوجهة',
    'finance.debtTitle': 'الديون والقروض',
    'finance.debtSubtitle': 'تتبع الأموال المقترضة أو المُقرضة بوضوح',
    'finance.debtStatusLent': 'لقد أقرضت مالًا',
    'finance.debtStatusBorrowed': 'لقد اقترضت مالًا',
    'finance.borrowed': 'اقترضت',
    'finance.lent': 'أقرضت',
    'finance.person': 'الاسم / الشخص',
    'finance.personPlaceholder': 'لمن هذا الدين؟',
    'finance.expectedReturn': 'تاريخ الاسترداد المتوقع',
    'finance.selectDateHint': 'اختر تاريخًا',
    'finance.clear': 'مسح',
    'finance.expectedPlaceholder': 'لم يتم تحديد تاريخ الاسترداد',
    'finance.deleteDebtTitle': 'حذف الدين',
    'finance.deleteDebtMessage': 'هل أنت متأكد من حذف هذا الدين؟ لا يمكن التراجع عن هذا الإجراء.',
  },
};

const FALLBACK_LOCALE: LocaleCode = 'en';

export const useTranslation = () => {
  const language = useSettingsStore((state) => state.language) as LocaleCode;

  const dictionary = useMemo(() => translations[language] ?? translations[FALLBACK_LOCALE], [
    language,
  ]);

  const t = useCallback(
    (key: string) => dictionary[key] ?? translations[FALLBACK_LOCALE][key] ?? key,
    [dictionary]
  );

  return { t, language: language ?? FALLBACK_LOCALE };
};
